# Generated by Django 4.1.7 on 2023-05-18 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': ('product',), 'verbose_name_plural': 'products'},
        ),
    ]
